apiVersion: v1
kind: Pod
spec:
  containers:
    - name: kube
      image: roffe/kubectl
      command: ["cat"]
      tty: true
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: Always
      command:
        - /busybox/cat
      tty: true
      volumeMounts:
        - name: jenkins-docker-cfg
          mountPath: /kaniko/.docker
  volumes:
    - name: jenkins-docker-cfg
      projected:
        sources:
          - secret:
              name: registry
              items:
                - key: .dockerconfigjson
                  path: config.json
