apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.provider: nginx
  name: node-app
  namespace: $APPNAME
spec:
  rules:
  - host: $APPNAME.easlab.co.uk
    http:
      paths:
      - backend:
          serviceName: node-app
          servicePort: 80
  tls:
  - hosts:
    - $APPNAME.easlab.co.uk
    secretName: $APPNAME-tls-cert